// Generated by delombok at Sun Mar 24 19:34:08 CDT 2019
package com.eden.orchid.api.publication;

import com.eden.orchid.Orchid;
import com.eden.orchid.api.OrchidContext;
import com.eden.orchid.api.options.annotations.Description;
import com.eden.orchid.api.options.annotations.Option;
import javax.inject.Inject;
import javax.inject.Singleton;
import java.util.Set;
import java.util.TreeSet;

/**
 * @since v1.0.0
 * @orchidApi services
 */
@Singleton
@Description(value = "How Orchid publishes your site to production.", name = "Publications")
public final class PublicationServiceImpl implements PublicationService {
    private final Set<OrchidPublisher> allPublishers;
    private OrchidContext context;
    @Option
    @Description("The publication pipeline stages")
    private PublicationPipeline stages;

    @Inject
    public PublicationServiceImpl(Set<OrchidPublisher> publishers) {
        this.allPublishers = new TreeSet<>(publishers);
    }

    @Override
    public void initialize(OrchidContext context) {
        this.context = context;
    }

// Indexing phase
//----------------------------------------------------------------------------------------------------------------------
    @Override
    public boolean publishAll(boolean dryDeploy) {
        return stages.publishAll(dryDeploy, (progress, maxProgress) -> context.broadcast(Orchid.Lifecycle.ProgressEvent.fire(this, "deploying", progress, maxProgress)));
    }

    @java.lang.SuppressWarnings("all")
    public PublicationPipeline getStages() {
        return this.stages;
    }

    @java.lang.SuppressWarnings("all")
    public void setStages(final PublicationPipeline stages) {
        this.stages = stages;
    }
}
