site:
  about:
    siteName: Orchid
    siteDescription: A beautiful and truly unique documentation engine and static site generator.
    avatar: 'assets/media/avatar.jpg'

theme:
  useSidebarSearch: true
  social:
    github: 'JavaEden/Orchid'
    twitter: 'OrchidSSG'
  primaryColor: '#7E80CF'
  bannerColor: '#444444'
  linkColor: '#7E80CF'
  trianglifyOptions:
    x_colors: 'BuPu'
    cell_size: 55
    seed: 1
  menu:
    - type: 'page'
      itemId: 'Quick-Start'
      title: 'Get Started'
    - type: 'wikiSections'
    - type: 'submenu'
      title: 'Explore'
      menu:
        - type: 'taxonomy'
          taxonomyType: 'group'
          includeTerms: true
          termsAtRoot: true
        - type: 'page'
          title: 'API Docs'
          itemId: 'com.eden.orchid'
        - type: 'page'
          title: 'Changelog'
          itemId: 'Changelog'
    - type: 'link'
      title: 'Github'
      url: 'https://github.com/JavaEden/Orchid'
  extraCss:
    - 'assets/css/pygments.scss'
    - 'assets/css/extras.scss'

services:
  publications:
    stages:
      - type: githubReleases
        repo: 'JavaEden/Orchid'

kotlindoc:
  sourceDirs:
    - '../../main/java'
    - '../../main/kotlin'

allPages:
  extraCss:
    - "inline:sidecar.css: .gitter-chat-embed { margin-top: 50px; }"
  extraJs:
    - "inline:sidecar.js:((window.gitter = { }).chat = { }).options = { room: 'JavaEden/Orchid' }; "
    - "https://sidecar.gitter.im/dist/sidecar.v1.js"

