package com.eden.orchid.wiki.pages

import com.eden.orchid.api.generators.OrchidCollection
import com.eden.orchid.api.generators.OrchidGenerator
import com.eden.orchid.api.options.annotations.Description
import java.util.stream.Stream

@Description("A collection of all PDFs generated by the Wiki plugin.")
class WikiBookCollection(
    generator: OrchidGenerator,
    items: List<WikiBookPage>
) : OrchidCollection<WikiBookPage>(generator.key, "books", items) {

    public override fun find(id: String): Stream<WikiBookPage> {
        return items
            .stream()
            .filter { page -> page.title == id }
    }

}