package com.eden.orchid.wiki.pages

import com.eden.orchid.api.generators.OrchidCollection
import com.eden.orchid.api.generators.OrchidGenerator
import com.eden.orchid.api.options.annotations.Description

@Description("A collection of all PDFs generated by the Wiki plugin.")
class WikiBookCollection(
    generator: OrchidGenerator,
    items: List<WikiBookPage>
) : OrchidCollection<WikiBookPage>(generator, "books", { items.stream() })