/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    /**
     * https://copper-leaf.github.io/kodiak */
    const val common_formatter: String = "com.eden.kodiak:common-formatter:" +
            Versions.com_eden_kodiak

    /**
     * https://copper-leaf.github.io/kodiak */
    const val common_models: String = "com.eden.kodiak:common-models:" + Versions.com_eden_kodiak

    /**
     * https://copper-leaf.github.io/kodiak */
    const val common_runner: String = "com.eden.kodiak:common-runner:" + Versions.com_eden_kodiak

    /**
     * https://copper-leaf.github.io/kodiak */
    const val com_eden_kodiak_dokka_runner: String = "com.eden.kodiak:dokka-runner:" +
            Versions.com_eden_kodiak

    /**
     * https://copper-leaf.github.io/kodiak */
    const val com_eden_kodiak_groovydoc_runner: String = "com.eden.kodiak:groovydoc-runner:" +
            Versions.com_eden_kodiak

    /**
     * https://copper-leaf.github.io/kodiak */
    const val com_eden_kodiak_javadoc_runner: String = "com.eden.kodiak:javadoc-runner:" +
            Versions.com_eden_kodiak

    /**
     * https://javaeden.github.io/Clog/Clog4j */
    const val clog4j: String = "com.eden:Clog4j:" + Versions.clog4j

    /**
     * https://javaeden.github.io/Common/Common */
    const val com_eden_common: String = "com.eden:Common:" + Versions.com_eden_common

    /**
     * https://copper-leaf.github.io/dokka-json */
    const val com_eden_dokka_runner: String = "com.eden:dokka-runner:" +
            Versions.com_eden_dokka_runner

    /**
     * https://copper-leaf.github.io/dokka-json */
    const val com_eden_groovydoc_runner: String = "com.eden:groovydoc-runner:" +
            Versions.com_eden_groovydoc_runner

    /**
     * https://copper-leaf.github.io/dokka-json */
    const val com_eden_javadoc_runner: String = "com.eden:javadoc-runner:" +
            Versions.com_eden_javadoc_runner

    /**
     * https://copper-leaf.github.io/krow */
    const val krow: String = "com.eden:krow:" + Versions.krow

    const val american_bible_society_client: String =
            "com.github.JavaEden:American-Bible-Society-Client:" +
            Versions.american_bible_society_client

    const val eden: String = "com.github.JavaEden:Eden:" + Versions.eden

    /**
     * https://www.codacy.com */
    const val codacy_coverage_reporter: String = "com.github.codacy:codacy-coverage-reporter:" +
            Versions.codacy_coverage_reporter

    /**
     * https://github.com/google/guice */
    const val guice: String = "com.google.inject:guice:" + Versions.guice

    const val gradle_bintray_plugin: String = "com.jfrog.bintray.gradle:gradle-bintray-plugin:" +
            Versions.gradle_bintray_plugin

    /**
     * http://moandjiezana.com/toml/toml4j */
    const val toml4j: String = "com.moandjiezana.toml:toml4j:" + Versions.toml4j

    const val openhtmltopdf_core: String = "com.openhtmltopdf:openhtmltopdf-core:" +
            Versions.com_openhtmltopdf

    const val openhtmltopdf_pdfbox: String = "com.openhtmltopdf:openhtmltopdf-pdfbox:" +
            Versions.com_openhtmltopdf

    const val openhtmltopdf_slf4j: String = "com.openhtmltopdf:openhtmltopdf-slf4j:" +
            Versions.com_openhtmltopdf

    const val openhtmltopdf_svg_support: String = "com.openhtmltopdf:openhtmltopdf-svg-support:" +
            Versions.com_openhtmltopdf

    /**
     * https://github.com/square/okhttp */
    const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.okhttp

    /**
     * http://github.com/univocity/univocity-parsers */
    const val univocity_parsers: String = "com.univocity:univocity-parsers:" +
            Versions.univocity_parsers

    /**
     * https://github.com/vsch/flexmark-java */
    const val flexmark_ext_aside: String = "com.vladsch.flexmark:flexmark-ext-aside:" +
            Versions.com_vladsch_flexmark

    /**
     * https://github.com/vsch/flexmark-java */
    const val flexmark_ext_attributes: String = "com.vladsch.flexmark:flexmark-ext-attributes:" +
            Versions.com_vladsch_flexmark

    /**
     * https://github.com/vsch/flexmark-java */
    const val flexmark_ext_enumerated_reference: String =
            "com.vladsch.flexmark:flexmark-ext-enumerated-reference:" +
            Versions.com_vladsch_flexmark

    /**
     * https://github.com/vsch/flexmark-java */
    const val flexmark_ext_gfm_tables: String = "com.vladsch.flexmark:flexmark-ext-gfm-tables:" +
            Versions.com_vladsch_flexmark

    /**
     * https://github.com/vsch/flexmark-java */
    const val flexmark_ext_gfm_tasklist: String =
            "com.vladsch.flexmark:flexmark-ext-gfm-tasklist:" + Versions.com_vladsch_flexmark

    /**
     * https://github.com/vsch/flexmark-java */
    const val flexmark_ext_toc: String = "com.vladsch.flexmark:flexmark-ext-toc:" +
            Versions.com_vladsch_flexmark

    /**
     * https://github.com/vsch/flexmark-java */
    const val flexmark: String = "com.vladsch.flexmark:flexmark:" + Versions.com_vladsch_flexmark

    /**
     * http://commons.apache.org/proper/commons-io/ */
    const val commons_io: String = "commons-io:commons-io:" + Versions.commons_io

    const val buildsrcversions: String = "de.fayard:buildSrcVersions:" + Versions.buildsrcversions

    const val task_tree: String = "gradle.plugin.com.dorongold.plugins:task-tree:" +
            Versions.task_tree

    /**
     * https://gitlab.com/jsass/jsass */
    const val jsass: String = "io.bit3:jsass:" + Versions.jsass

    /**
     * https://github.com/classgraph/classgraph */
    const val classgraph: String = "io.github.classgraph:classgraph:" + Versions.classgraph

    /**
     * http://pebbletemplates.io */
    const val pebble: String = "io.pebbletemplates:pebble:" + Versions.pebble

    /**
     * https://strikt.io/ */
    const val strikt_core: String = "io.strikt:strikt-core:" + Versions.strikt_core

    const val javax_inject: String = "javax.inject:javax.inject:" + Versions.javax_inject

    /**
     * http://beanvalidation.org */
    const val validation_api: String = "javax.validation:validation-api:" + Versions.validation_api

    /**
     * https://github.com/javaee/jaxb-spec */
    const val jaxb_api: String = "javax.xml.bind:jaxb-api:" + Versions.jaxb_api

    /**
     * http://code.google.com/p/thumbnailator */
    const val thumbnailator: String = "net.coobird:thumbnailator:" + Versions.thumbnailator

    /**
     * http://plantuml.sourceforge.net */
    const val plantuml: String = "net.sourceforge.plantuml:plantuml:" + Versions.plantuml

    /**
     * https://github.com/ajoberstar/gradle-git */
    const val gradle_git: String = "org.ajoberstar:gradle-git:" + Versions.gradle_git

    /**
     * http://commons.apache.org/proper/commons-lang/ */
    const val commons_lang3: String = "org.apache.commons:commons-lang3:" + Versions.commons_lang3

    /**
     * https://github.com/asciidoctor/asciidoctorj */
    const val asciidoctorj: String = "org.asciidoctor:asciidoctorj:" + Versions.asciidoctorj

    /**
     * http://atteo.org/static/evo-inflector */
    const val evo_inflector: String = "org.atteo:evo-inflector:" + Versions.evo_inflector

    /**
     * http://uel.java.net */
    const val javax_el: String = "org.glassfish:javax.el:" + Versions.javax_el

    /**
     * http://hamcrest.org/JavaHamcrest/ */
    const val hamcrest_library: String = "org.hamcrest:hamcrest-library:" +
            Versions.hamcrest_library

    /**
     * http://hibernate.org/validator */
    const val hibernate_validator: String = "org.hibernate.validator:hibernate-validator:" +
            Versions.hibernate_validator

    /**
     * https://kotlinlang.org/ */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://github.com/Kotlin/kotlinx.html */
    const val kotlinx_html_jvm: String = "org.jetbrains.kotlinx:kotlinx-html-jvm:" +
            Versions.kotlinx_html_jvm

    const val json: String = "org.json:json:" + Versions.json

    /**
     * https://jsoup.org/ */
    const val jsoup: String = "org.jsoup:jsoup:" + Versions.jsoup

    /**
     * https://junit.org/junit5/ */
    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:" +
            Versions.org_junit_jupiter

    /**
     * https://junit.org/junit5/ */
    const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:" +
            Versions.org_junit_jupiter

    /**
     * https://junit.org/junit5/ */
    const val junit_jupiter_params: String = "org.junit.jupiter:junit-jupiter-params:" +
            Versions.org_junit_jupiter

    /**
     * https://github.com/mockito/mockito */
    const val mockito_core: String = "org.mockito:mockito-core:" + Versions.mockito_core

    /**
     * http://www.nanohttpd.org */
    const val nanohttpd_websocket: String = "org.nanohttpd:nanohttpd-websocket:" +
            Versions.org_nanohttpd

    /**
     * http://www.nanohttpd.org */
    const val nanohttpd: String = "org.nanohttpd:nanohttpd:" + Versions.org_nanohttpd

    /**
     * http://www.pygments.org */
    const val pygments: String = "org.pygments:pygments:" + Versions.pygments

    /**
     * http://www.jython.org/ */
    const val jython_standalone: String = "org.python:jython-standalone:" +
            Versions.jython_standalone

    /**
     * http://www.snakeyaml.org */
    const val snakeyaml: String = "org.yaml:snakeyaml:" + Versions.snakeyaml
}
