
object Modules {
    val OrchidCore = Module(":orchid-core")
    val OrchidTest = Module(":orchid-test")

    val OrchidAll               = Module(":bundles:orchid-all-bundle")
    val OrchidBlog              = Module(":bundles:orchid-blog-bundle")
    val OrchidDocs              = Module(":bundles:orchid-docs-bundle")
    val OrchidLanguagePack      = Module(":bundles:orchid-languages-bundle")

    val OrchidArchives          = Module(":features:orchid-archives-feature")
    val OrchidAsciidoc          = Module(":features:orchid-asciidoc-feature")
    val OrchidAzure             = Module(":features:orchid-azure-feature")
    val OrchidBible             = Module(":features:orchid-bible-feature")
    val OrchidBitbucket         = Module(":features:orchid-bitbucket-feature")
    val OrchidChangelog         = Module(":features:orchid-changelog-feature")
    val OrchidDiagrams          = Module(":features:orchid-diagrams-feature")
    val OrchidForms             = Module(":features:orchid-forms-feature")
    val OrchidGithub            = Module(":features:orchid-github-feature")
    val OrchidGitlab            = Module(":features:orchid-gitlab-feature")
    val OrchidGroovydoc         = Module(":features:orchid-groovydoc-feature")
    val OrchidJavadoc           = Module(":features:orchid-javadoc-feature")
    val OrchidKotlindoc         = Module(":features:orchid-kotlindoc-feature")
    val OrchidKSS               = Module(":features:orchid-kss-feature")
    val OrchidNetlify           = Module(":features:orchid-netlify-feature")
    val OrchidNetlifyCMS        = Module(":features:orchid-netlify-cms-feature")
    val OrchidPages             = Module(":features:orchid-pages-feature")
    val OrchidPluginDocs        = Module(":features:orchid-plugin-docs-feature")
    val OrchidPosts             = Module(":features:orchid-posts-feature")
    val OrchidPresentations     = Module(":features:orchid-presentations-feature")
    val OrchidSearch            = Module(":features:orchid-search-feature")
    val OrchidSnippets          = Module(":features:orchid-snippets-feature")
    val OrchidSourceDoc         = Module(":features:orchid-sourcedoc-feature")
    val OrchidSwagger           = Module(":features:orchid-swagger-feature")
    val OrchidSwiftdoc          = Module(":features:orchid-swiftdoc-feature")
    val OrchidSyntaxHighlighter = Module(":features:orchid-syntax-highlighter-feature")
    val OrchidWiki              = Module(":features:orchid-wiki-feature")
    val OrchidWritersBlocks     = Module(":features:orchid-writers-blocks-feature")

    val OrchidBsDoc           = Module(":themes:orchid-bsdoc-theme")
    val OrchidCopper          = Module(":themes:orchid-copper-theme")
    val OrchidEditorial       = Module(":themes:orchid-editorial-theme")
    val OrchidFutureImperfect = Module(":themes:orchid-future-imperfect-theme")
}
