// Generated by delombok at Sun Mar 24 19:34:08 CDT 2019
package com.eden.orchid.api.generators;

import com.eden.orchid.api.options.annotations.Description;
import com.eden.orchid.api.theme.pages.OrchidPage;
import java.util.List;
import java.util.stream.Stream;

@Description("A Folder Collection represents a collection of OrchidPages that are located as a batch from a specified folder in your resources. A page is matched from a Folder Collection with an \'itemId\' matching the page\'s title.")
public class FolderCollection extends OrchidCollection<OrchidPage> {
    private final String resourceRoot;
    private final Class<? extends OrchidPage> pageClass;
    private boolean canCreate = true;
    private boolean canDelete = true;
    private String slugFormat = "{slug}";

    public FolderCollection(OrchidGenerator generator, String collectionId, List<OrchidPage> items, Class<? extends OrchidPage> pageClass, String resourceRoot) {
        this(generator.getKey(), collectionId, items, pageClass, resourceRoot);
    }

    public FolderCollection(String collectionType, String collectionId, List<OrchidPage> items, Class<? extends OrchidPage> pageClass, String resourceRoot) {
        super(collectionType, collectionId, items);
        this.resourceRoot = resourceRoot;
        this.pageClass = pageClass;
    }

    public Stream<OrchidPage> find(String id) {
        return getItems().stream().filter(page -> page.getTitle().equals(id));
    }

    public String getResourceRoot() {
        return this.resourceRoot;
    }

    public Class<? extends OrchidPage> getPageClass() {
        return this.pageClass;
    }

    public boolean isCanCreate() {
        return this.canCreate;
    }

    public void setCanCreate(final boolean canCreate) {
        this.canCreate = canCreate;
    }

    public boolean isCanDelete() {
        return this.canDelete;
    }

    public void setCanDelete(final boolean canDelete) {
        this.canDelete = canDelete;
    }

    public String getSlugFormat() {
        return this.slugFormat;
    }

    public void setSlugFormat(final String slugFormat) {
        this.slugFormat = slugFormat;
    }
}
