// Generated by delombok at Sun Mar 24 19:34:08 CDT 2019
package com.eden.orchid.testhelpers;

import java.util.Map;
import java.util.stream.Collectors;

public class TestResults {
    public final Map<String, TestRenderer.TestRenderedPage> renderedPageMap;
    public final boolean renderingSuccess;
    public final Throwable thrownException;

    @Override
    public String toString() {
        return "TestResults: " + (renderingSuccess ? "success" : "failure") + " with " + renderedPageMap.size() + " pages";
    }

    public String showResults() {
        if (renderedPageMap.size() == 0) {
            return "(empty site)";
        } else {
            return renderedPageMap.keySet().stream().sorted().collect(Collectors.joining("\n"));
        }
    }

    public TestResults printResults() {
        System.out.println(showResults());
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public TestResults(final Map<String, TestRenderer.TestRenderedPage> renderedPageMap, final boolean renderingSuccess, final Throwable thrownException) {
        this.renderedPageMap = renderedPageMap;
        this.renderingSuccess = renderingSuccess;
        this.thrownException = thrownException;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isRenderingSuccess() {
        return this.renderingSuccess;
    }

    @java.lang.SuppressWarnings("all")
    public Throwable getThrownException() {
        return this.thrownException;
    }
}
