// Generated by delombok at Sun Mar 24 19:34:08 CDT 2019
package com.eden.orchid.api.server;

import com.eden.orchid.api.OrchidContext;
import javax.inject.Inject;
import javax.inject.Singleton;
import java.io.IOException;
import java.util.Set;

@Singleton
public class OrchidServer {
    private final OrchidContext context;
    private int httpServerPort;
    private int websocketPort;
    public OrchidWebserver server;
    public OrchidWebsocket websocket;
    private final Set<OrchidController> controllers;
    private final OrchidFileController fileController;

    @Inject
    public OrchidServer(OrchidContext context, Set<OrchidController> controllers, OrchidFileController fileController) {
        this.context = context;
        this.controllers = controllers;
        this.fileController = fileController;
    }

    public void start(int port) throws IOException {
        // TODO: setup assistedInject for these
        this.server = new OrchidWebserver(context, controllers, fileController, port);
        this.httpServerPort = this.server.getListeningPort();
        this.websocket = new OrchidWebsocket(context, port);
        this.websocketPort = this.websocket.getListeningPort();
    }

    @java.lang.SuppressWarnings("all")
    public OrchidContext getContext() {
        return this.context;
    }

    @java.lang.SuppressWarnings("all")
    public int getHttpServerPort() {
        return this.httpServerPort;
    }

    @java.lang.SuppressWarnings("all")
    public int getWebsocketPort() {
        return this.websocketPort;
    }

    @java.lang.SuppressWarnings("all")
    public OrchidWebserver getServer() {
        return this.server;
    }

    @java.lang.SuppressWarnings("all")
    public OrchidWebsocket getWebsocket() {
        return this.websocket;
    }

    @java.lang.SuppressWarnings("all")
    public Set<OrchidController> getControllers() {
        return this.controllers;
    }

    @java.lang.SuppressWarnings("all")
    public OrchidFileController getFileController() {
        return this.fileController;
    }
}
