// Generated by delombok at Sun Mar 24 19:34:08 CDT 2019
package com.eden.orchid.api.theme.components;

import com.eden.orchid.api.options.OptionsHolder;

public interface ModularType extends OptionsHolder {

    String getType();

}
